# Form implementation generated from reading ui file 'changelog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_changelog(object):
    def setupUi(self, changelog):
        changelog.setObjectName("changelog")
        changelog.resize(341, 245)
        changelog.setMinimumSize(QtCore.QSize(341, 245))
        changelog.setMaximumSize(QtCore.QSize(341, 245))
        changelog.setWindowTitle("")
        changelog.setStyleSheet("QWidget {    background-color: #5A5A5A; }\n"
"\n"
"QPushButton {\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    background-color: #3a3a3a;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton::pressed { background-color: #2d5bd4; }")
        self.chlog_close_btn = QtWidgets.QPushButton(parent=changelog)
        self.chlog_close_btn.setGeometry(QtCore.QRect(250, 200, 81, 32))
        self.chlog_close_btn.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chlog_close_btn.setFont(font)
        self.chlog_close_btn.setText("")
        self.chlog_close_btn.setObjectName("chlog_close_btn")
        self.title_desc_lbl = QtWidgets.QLabel(parent=changelog)
        self.title_desc_lbl.setGeometry(QtCore.QRect(0, 55, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title_desc_lbl.setFont(font)
        self.title_desc_lbl.setStyleSheet("background-color: rgb(22, 97, 167);")
        self.title_desc_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.title_desc_lbl.setObjectName("title_desc_lbl")
        self.title_lbl = QtWidgets.QLabel(parent=changelog)
        self.title_lbl.setGeometry(QtCore.QRect(-3, 0, 345, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(48)
        self.title_lbl.setFont(font)
        self.title_lbl.setStyleSheet("background-color: rgb(22, 97, 167);")
        self.title_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_lbl.setIndent(-1)
        self.title_lbl.setObjectName("title_lbl")
        self.chlog_version_lbl = QtWidgets.QLabel(parent=changelog)
        self.chlog_version_lbl.setGeometry(QtCore.QRect(20, 85, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chlog_version_lbl.setFont(font)
        self.chlog_version_lbl.setObjectName("chlog_version_lbl")
        self.chlog_line_1_lbl = QtWidgets.QLabel(parent=changelog)
        self.chlog_line_1_lbl.setGeometry(QtCore.QRect(20, 115, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chlog_line_1_lbl.setFont(font)
        self.chlog_line_1_lbl.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.chlog_line_1_lbl.setText("")
        self.chlog_line_1_lbl.setObjectName("chlog_line_1_lbl")
        self.bg_lbl = QtWidgets.QLabel(parent=changelog)
        self.bg_lbl.setGeometry(QtCore.QRect(5, 105, 331, 77))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bg_lbl.setFont(font)
        self.bg_lbl.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 5px;")
        self.bg_lbl.setText("")
        self.bg_lbl.setObjectName("bg_lbl")
        self.chlog_line_2_lbl = QtWidgets.QLabel(parent=changelog)
        self.chlog_line_2_lbl.setGeometry(QtCore.QRect(20, 135, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chlog_line_2_lbl.setFont(font)
        self.chlog_line_2_lbl.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.chlog_line_2_lbl.setText("")
        self.chlog_line_2_lbl.setObjectName("chlog_line_2_lbl")
        self.chlog_line_3_lbl = QtWidgets.QLabel(parent=changelog)
        self.chlog_line_3_lbl.setGeometry(QtCore.QRect(20, 155, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chlog_line_3_lbl.setFont(font)
        self.chlog_line_3_lbl.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.chlog_line_3_lbl.setText("")
        self.chlog_line_3_lbl.setObjectName("chlog_line_3_lbl")
        self.title_lbl.raise_()
        self.bg_lbl.raise_()
        self.chlog_close_btn.raise_()
        self.title_desc_lbl.raise_()
        self.chlog_version_lbl.raise_()
        self.chlog_line_1_lbl.raise_()
        self.chlog_line_2_lbl.raise_()
        self.chlog_line_3_lbl.raise_()

        self.retranslateUi(changelog)
        QtCore.QMetaObject.connectSlotsByName(changelog)

    def retranslateUi(self, changelog):
        _translate = QtCore.QCoreApplication.translate
        self.title_desc_lbl.setText(_translate("changelog", "Ayckinn\'s Password Generator"))
        self.title_lbl.setText(_translate("changelog", "GENPASS"))
        self.chlog_version_lbl.setText(_translate("changelog", "Version 1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    changelog = QtWidgets.QWidget()
    ui = Ui_changelog()
    ui.setupUi(changelog)
    changelog.show()
    sys.exit(app.exec())
