# Form implementation generated from reading ui file 'lang.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Lang(object):
    def setupUi(self, Lang):
        Lang.setObjectName("Lang")
        Lang.resize(360, 192)
        Lang.setMinimumSize(QtCore.QSize(360, 192))
        Lang.setMaximumSize(QtCore.QSize(360, 192))
        Lang.setStyleSheet("QWidget {    background-color: #5A5A5A; }\n"
"\n"
"QPushButton {\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    background-color: #3a3a3a;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton::pressed { background-color: #2d5bd4; }")
        self.lang_title_lbl = QtWidgets.QLabel(parent=Lang)
        self.lang_title_lbl.setGeometry(QtCore.QRect(0, 0, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(48)
        self.lang_title_lbl.setFont(font)
        self.lang_title_lbl.setStyleSheet("background-color: rgb(22, 97, 167);")
        self.lang_title_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lang_title_lbl.setIndent(-1)
        self.lang_title_lbl.setObjectName("lang_title_lbl")
        self.lang_sub_title_lbl = QtWidgets.QLabel(parent=Lang)
        self.lang_sub_title_lbl.setGeometry(QtCore.QRect(-1, 55, 362, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lang_sub_title_lbl.setFont(font)
        self.lang_sub_title_lbl.setStyleSheet("background-color: rgb(22, 97, 167);")
        self.lang_sub_title_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lang_sub_title_lbl.setObjectName("lang_sub_title_lbl")
        self.label = QtWidgets.QLabel(parent=Lang)
        self.label.setGeometry(QtCore.QRect(0, 90, 361, 21))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=Lang)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 140, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.en_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.en_btn.setFont(font)
        self.en_btn.setObjectName("en_btn")
        self.horizontalLayout.addWidget(self.en_btn)
        self.fr_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fr_btn.setFont(font)
        self.fr_btn.setObjectName("fr_btn")
        self.horizontalLayout.addWidget(self.fr_btn)

        self.retranslateUi(Lang)
        QtCore.QMetaObject.connectSlotsByName(Lang)

    def retranslateUi(self, Lang):
        _translate = QtCore.QCoreApplication.translate
        Lang.setWindowTitle(_translate("Lang", "Language - Langue"))
        self.lang_title_lbl.setText(_translate("Lang", "GENPASS"))
        self.lang_sub_title_lbl.setText(_translate("Lang", "Ayckinn\'s Password Generator"))
        self.label.setText(_translate("Lang", "Choose your language / Choisissez votre langue"))
        self.en_btn.setText(_translate("Lang", "English"))
        self.fr_btn.setText(_translate("Lang", "Français"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Lang = QtWidgets.QWidget()
    ui = Ui_Lang()
    ui.setupUi(Lang)
    Lang.show()
    sys.exit(app.exec())
